# Generated by Django 5.1.7 on 2025-03-09 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
