# Generated by Django 5.1.7 on 2025-03-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Features',
            },
        ),
        migrations.RemoveField(
            model_name='listings',
            name='features',
        ),
        migrations.AddField(
            model_name='listings',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='listings', to='listing.feature'),
        ),
    ]
