# Generated by Django 5.1.7 on 2025-03-09 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_alter_listings_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='size',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='units',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
