# Generated by Django 5.1.7 on 2025-04-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_listings_country_alter_listings_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
