# Generated by Django 5.1.7 on 2025-04-08 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_listings_is_listed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='units',
        ),
    ]
