# Generated by Django 5.1.7 on 2025-04-09 17:30

import listing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimages',
            name='image',
            field=models.ImageField(upload_to=listing.models.listing_images_directory_path),
        ),
    ]
