# Generated by Django 5.1.7 on 2025-04-09 17:45

import listing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_alter_listingimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimages',
            name='image',
            field=models.ImageField(max_length=500, upload_to=listing.models.listing_images_directory_path),
        ),
    ]
