# Generated by Django 5.1.7 on 2025-04-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_alter_listingimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='cover_image',
            field=models.ImageField(max_length=500, upload_to='listing-cover/'),
        ),
    ]
