# Generated by Django 5.1.7 on 2025-04-09 21:00

import listing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_alter_listings_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='cover_image',
            field=models.ImageField(max_length=500, upload_to=listing.models.cover_image_directory_path),
        ),
    ]
