# Generated by Django 5.2 on 2025-05-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_alter_listings_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='keywords',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
