# Generated by Django 5.2 on 2025-05-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_listings_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
