"""
Django settings for eaglespoint project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import environ



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# for linking env secrets
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-fr85#p0^htm)3g+wm8@^f@7_l-z#sb1(uw42hv-33fsfma$aab'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['.vercel.app', '*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'core',
    'user',
    'listing',
    'adminv2',
    'messaging',
    'blog',

    'django_components',
    'django_ckeditor_5',
]

AUTH_USER_MODEL = 'user.CustomUser' # updated
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',  # updated
]
LOGIN_URL = '/user/login/' #updated

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "django_components.middleware.ComponentDependencyMiddleware", #django-component
    "whitenoise.middleware.WhiteNoiseMiddleware", #whitenoise
]

ROOT_URLCONF = 'eaglespoint.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': False,  # Should be False if using custom loaders
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                    'django_components.template_loader.Loader',
                ])
            ],
            'builtins': [  # Add builtins correctly
                'django_components.templatetags.component_tags',
            ],
        },
    },
]



WSGI_APPLICATION = 'eaglespoint.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

""" DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
} """

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME'),
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
        'OPTIONS': {
            'ssl': {
                'ca': str(BASE_DIR / 'cert/ca.pem'),
            }
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Ensures Django can find static files
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#ADDED SETTINGS

# MEDIA_URL = '/media/'
B2_MEDIA_URL = "https://eaglespoint-website.s3.eu-central-003.backblazeb2.com/"
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media') 
# MEDIA_ROOT = "https://eaglespoint-website.s3.eu-central-003.backblazeb2.com/"

from django_components import ComponentsSettings

COMPONENTS = ComponentsSettings(
    dirs=[
        Path(BASE_DIR) / "components",
    ],
)

STATICFILES_FINDERS = [
    # Default finders
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    # Django components
    "django_components.finders.ComponentsFileSystemFinder",
]



AWS_ACCESS_KEY_ID = env('B2_ACCESS_KEY')
AWS_SECRET_ACCESS_KEY = env('B2_SECRET_KEY')
AWS_STORAGE_BUCKET_NAME = env('B2_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = env('B2_ENDPOINT')
AWS_S3_REGION_NAME = env("B2_REGION")
AWS_S3_ADDRESSING_STYLE = "path"

STORAGES = {
    "default": {
        # "BACKEND": "django.core.files.storage.FileSystemStorage",
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        "OPTIONS": {
            "access_key": env('B2_ACCESS_KEY'),
            "secret_key": env('B2_SECRET_KEY'),
            "bucket_name": env('B2_BUCKET_NAME'),
            "region_name": env('B2_REGION'),
            "endpoint_url": env('B2_ENDPOINT'),
            "default_acl": None,  
            "file_overwrite": False, 
        },
    },
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            # if DEBUG
            # else "whitenoise.storage.CompressedManifestStaticFilesStorage"
            # # else "django.contrib.staticfiles.storage.StaticFilesStorage"
        ),
    },
}

#timezone
TIME_ZONE = 'Africa/Lagos'
USE_TZ = True

#Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False  
EMAIL_TIMEOUT = 30
EMAIL_HOST_USER = env('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = env('EMAIL_APP_PASSWORD')

# CKEditor 5 Configuration
CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList',
            'blockQuote', 'imageUpload', 'insertTable', 'fontSize', 'fontColor'
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', 'imageStyle:alignLeft',
                'imageStyle:alignCenter', 'imageStyle:alignRight'
            ],
            'styles': ['full', 'alignLeft', 'alignCenter', 'alignRight']
        },
    },
    'extends': {
        'language': 'en',
        'toolbar': [
            'heading', 'codeBlock', '|', 'bold', 'italic', 'link', 'underline',
            'strikethrough', 'subscript', 'superscript', 'highlight', '|',
            'bulletedList', 'numberedList', 'todoList', '|', 'blockQuote',
            'insertImage', 'insertTable', 'fontSize', 'fontFamily', 'fontColor',
            'removeFormat', 'sourceEditing'
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative', '|', 'imageStyle:alignLeft',
                'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',
                'toggleImageCaption'
            ],
            'styles': ['full', 'side', 'alignLeft', 'alignRight', 'alignCenter']
        },
    }
}

CKEDITOR_5_CUSTOM_CSS = 'path_to.css' # optional
CKEDITOR_5_FILE_STORAGE = "utils.storage.CustomS3Storage"
CKEDITOR_5_ALLOW_ALL_FILE_TYPES = False
CKEDITOR_5_UPLOAD_FILE_TYPES = ['jpeg', 'webp', 'jpg', 'png', 'gif']

