# Generated by Django 5.2 on 2025-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogarticle',
            name='image',
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/cover-images/'),
        ),
    ]
