# Generated by Django 5.2 on 2025-05-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_blogarticle_image_blogarticle_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
