# Generated by Django 5.2 on 2025-05-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogarticle_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
