# Generated by Django 5.2 on 2025-05-18 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0014_alter_listings_slug'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='listing.listings'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
