# Generated by Django 5.2 on 2025-05-24 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontent', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
