# Generated by Django 5.2 on 2025-05-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontent', '0003_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
