# Generated by Django 5.2 on 2025-06-03 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmscontent', '0005_partners'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partners',
            old_name='photo',
            new_name='logo',
        ),
    ]
