# Generated by Django 5.2 on 2025-05-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_profileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='country_code',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
