# Generated by Django 5.2 on 2025-06-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_block',
            field=models.BooleanField(default=False),
        ),
    ]
