# Generated by Django 5.2 on 2025-06-17 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_agents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agents',
            new_name='Agent',
        ),
    ]
