# Generated by Django 5.2 on 2025-06-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_agents_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='is_active',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='agent',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
